Update sphinx.yml

diff --git a/.github/workflows/sphinx.yml b/.github/workflows/sphinx.yml
--- a/.github/workflows/sphinx.yml
+++ b/.github/workflows/sphinx.yml
@@ -24,16 +24,20 @@ jobs:
       with:
         path: ~/id_file
         key: helperid-${{ github.run_id }}
+        action-id: ${{ github.run_id }}
 
     - name: Wait until repocheck in aux is complete
       run: |
-        helper_id=$(cat ~/id_file)
+        #helper_id=$(cat ~/id_file)
+        helper_id=$(cat ~)
         cd ${{ github.workspace }}/tests/ci
-        jobs_url=$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/actions/runs/$helper_id/jobs
-        conclusion=$(echo $jobs_url | ./check_status.py completion "Repo check")
-        if [[ $conclusion == "failure" ]]; then
-          exit 1
-        fi
+        #jobs_url=$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/actions/runs/$helper_id/jobs
+        jobs_url=$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/actions/runs
+        #conclusion=$(echo $jobs_url | ./check_status.py completion "Repo check")
+        conclusion=$(echo $jobs_url)
+        #if [[ $conclusion == "failure" ]]; then
+        #  exit 1
+        #fi
     - uses: actions/cache@v2
       with:
         path: ~/repocheck_file
